In [36]:
import cv2
import keras
import numpy as np
import matplotlib.pyplot as plt

In [11]:
image01 = cv2.imread("faces/img01.jpg")
cv2.imshow("Face",image01)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
face_image = []
for i in range(1, 16):
    temp_image = cv2.imread(f"faces/img{i:02d}.jpg")
    temp_image = cv2.resize(temp_image, (64,64))
    temp_image = cv2.cvtColor(temp_image, cv2.COLOR_BGR2RGB)
    face_image.append(temp_image)

In [13]:
print(face_image)

[array([[[  7,   8,  10],
        [  5,   7,   6],
        [ 14,  14,  14],
        ...,
        [212, 231, 235],
        [215, 235, 236],
        [214, 234, 233]],

       [[ 10,  11,  13],
        [  7,   8,   9],
        [ 12,  12,  12],
        ...,
        [206, 225, 229],
        [202, 222, 223],
        [208, 228, 227]],

       [[ 12,  13,  15],
        [  9,   9,  11],
        [ 10,  10,  11],
        ...,
        [206, 225, 227],
        [209, 229, 229],
        [212, 232, 230]],

       ...,

       [[103,  66,  48],
        [110,  73,  55],
        [111,  74,  55],
        ...,
        [215, 231, 231],
        [217, 233, 233],
        [217, 232, 235]],

       [[ 99,  62,  45],
        [110,  74,  56],
        [115,  78,  59],
        ...,
        [216, 232, 232],
        [217, 233, 234],
        [217, 232, 235]],

       [[ 97,  61,  45],
        [105,  70,  51],
        [108,  71,  53],
        ...,
        [217, 233, 233],
        [217, 232, 235],
        [216, 231, 234]

In [14]:
print(np.shape(face_image))

(15, 64, 64, 3)


In [15]:
animal_image = []
for i in range(1, 16):
    temp_image = cv2.imread(f"animals/img{i:02d}.jpg")
    temp_image = cv2.resize(temp_image, (64,64))
    temp_image = cv2.cvtColor(temp_image, cv2.COLOR_BGR2RGB)
    animal_image.append(temp_image)

In [16]:
print(animal_image)

[array([[[ 98, 135,  98],
        [167, 197, 166],
        [121, 140, 117],
        ...,
        [217, 197, 195],
        [236, 212, 211],
        [217, 197, 194]],

       [[106, 142, 109],
        [108, 138, 109],
        [117, 135, 113],
        ...,
        [225, 202, 207],
        [168, 144, 151],
        [ 93,  70,  74]],

       [[ 94, 126,  97],
        [160, 185, 159],
        [118, 134, 114],
        ...,
        [ 58,  55,  53],
        [ 22,  10,  11],
        [ 44,  21,  26]],

       ...,

       [[143, 151, 161],
        [ 46,  55,  62],
        [ 92, 101, 106],
        ...,
        [181, 176, 172],
        [144, 138, 138],
        [190, 180, 181]],

       [[ 47,  56,  64],
        [ 59,  67,  73],
        [ 38,  48,  50],
        ...,
        [188, 179, 177],
        [148, 138, 137],
        [163, 151, 150]],

       [[ 45,  54,  59],
        [ 77,  87,  89],
        [ 69,  79,  80],
        ...,
        [118, 106, 105],
        [111, 100,  98],
        [146, 132, 129]

In [17]:
print(np.shape(animal_image))

(15, 64, 64, 3)


In [21]:
images = np.array(face_image + animal_image)

In [22]:
print(images)

[[[[  7   8  10]
   [  5   7   6]
   [ 14  14  14]
   ...
   [212 231 235]
   [215 235 236]
   [214 234 233]]

  [[ 10  11  13]
   [  7   8   9]
   [ 12  12  12]
   ...
   [206 225 229]
   [202 222 223]
   [208 228 227]]

  [[ 12  13  15]
   [  9   9  11]
   [ 10  10  11]
   ...
   [206 225 227]
   [209 229 229]
   [212 232 230]]

  ...

  [[103  66  48]
   [110  73  55]
   [111  74  55]
   ...
   [215 231 231]
   [217 233 233]
   [217 232 235]]

  [[ 99  62  45]
   [110  74  56]
   [115  78  59]
   ...
   [216 232 232]
   [217 233 234]
   [217 232 235]]

  [[ 97  61  45]
   [105  70  51]
   [108  71  53]
   ...
   [217 233 233]
   [217 232 235]
   [216 231 234]]]


 [[[206 127  79]
   [207 132  93]
   [195 123  93]
   ...
   [232 144  95]
   [220 148  93]
   [217 154  98]]

  [[203 125  78]
   [201 127  87]
   [196 124  93]
   ...
   [234 145  97]
   [221 148  93]
   [213 149  93]]

  [[203 125  83]
   [199 124  85]
   [197 126  92]
   ...
   [228 142  93]
   [221 146  91]
   [217 150

In [23]:
print(np.shape(images))

(30, 64, 64, 3)


In [29]:
y = np.array([(0,1)]*15 + [(1,0)]*15)

In [30]:
print(y)

[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]


In [31]:
y = np.array(y)
print(y.shape)

(30, 2)


In [32]:
X_train = images/255.0

In [34]:
print(X_train.shape)

(30, 64, 64, 3)


In [38]:
model = keras.Sequential(name="practice_CNN")
model.add(keras.layers.Input(shape=(64,64,3)))
model.add(keras.layers.Conv2D(128,(3,3), activation='relu'))
model.add(keras.layers.MaxPooling2D(pool_size=(2,2), strides=None))
model.add(keras.layers.Conv2D(64,(3,3), activation='relu'))
model.add(keras.layers.MaxPooling2D(pool_size=(2,2), strides=None))
model.add(keras.layers.Conv2D(32,(3,3), activation='relu'))
model.add(keras.layers.MaxPooling2D(pool_size=(2,2), strides=None))
model.add(keras.layers.Conv2D(32,(3,3), activation='relu'))

model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(64, activation='relu'))
model.add(keras.layers.Dense(32, activation='relu'))
model.add(keras.layers.Dense(32, activation='relu'))
model.add(keras.layers.Dense(2, activation='softmax'))

In [39]:
model.summary()

Model: "practice_CNN"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 62, 62, 128)    │         3,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 31, 31, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 29, 29, 64)     │        73,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 14, 14, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 12, 12, 32)     │        18,464 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 6, 6, 32)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 4, 4, 32)       │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │        32,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 2)              │            66 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 141,122 (551.26 KB)

 Trainable params: 141,122 (551.26 KB)

 Non-trainable params: 0 (0.00 B)